import {
  ActProfile,
  ArtistAsset,
  ArtistProfile,
  ArtistWorkspace,
  Campaign,
} from "@/lib/types";

export const hamedWorkspace: ArtistWorkspace = {
  id: "WORKSPACE-HAMED",
  ownerName: "Hamed Sadeghi",
  businessName: "Hamed Sadeghi Music",
  baseCity: "Sydney, Australia",
  timezone: "Australia/Sydney",
  signatureName: "Hamed",
  defaultCurrency: "AUD",
  monthlyAiBudgetUsd: 10,
};

export const hamedActs: ActProfile[] = [
  {
    id: "ACT-EISHAN",
    name: "Eishan Ensemble",
    shortName: "Eishan",
    format: "International touring ensemble",
    genres: "Persian classical music, chamber jazz, Middle Eastern jazz fusion",
    baseCity: "Sydney, Australia",
    oneLinePitch:
      "Persian classical music reimagined through cross-cultural improvisation.",
    shortBio:
      "Led by Persian-Australian tar player and composer Hamed Sadeghi, Eishan Ensemble blends Persian musical traditions with contemporary jazz and has toured across Australia, Europe, and Asia.",
    achievements: [
      "ARIA-nominated ensemble",
      "Performed at WOMADelaide, London Jazz Festival, Rome Jazz Festival and Sydney Opera House",
      "Northern Rhapsody released in 2025",
    ],
    websiteUrl: "https://www.eishanensemble.com",
    source: "website",
    sourceUrl: "https://www.eishanensemble.com",
    confirmed: false,
  },
  {
    id: "ACT-HAMED-SOLO",
    name: "Hamed Sadeghi Solo",
    shortName: "Hamed Solo",
    format: "Solo tar performance and composition",
    genres: "Persian classical music, contemporary music, cross-cultural composition",
    baseCity: "Sydney, Australia",
    oneLinePitch:
      "Award-winning Persian-Australian tar player and composer bridging musical traditions.",
    shortBio:
      "Hamed Sadeghi is a Persian-Australian tar player and composer whose work spans solo performance, contemporary music, jazz, theatre, dance and film.",
    achievements: [
      "ARIA-nominated artist and composer",
      "APRA Art Music Award finalist",
      "Composer for major Australian theatre, dance and film organisations",
    ],
    websiteUrl: "https://www.hamedsadeghi.com",
    source: "website",
    sourceUrl: "https://www.hamedsadeghi.com/about",
    confirmed: false,
  },
  {
    id: "ACT-VAZESH",
    name: "Vazesh",
    shortName: "Vazesh",
    format: "Improvising trio",
    genres: "Spiritual jazz, Persian Radif, long-form improvisation",
    baseCity: "Sydney, Australia",
    oneLinePitch:
      "A fully improvised trio inspired by Persian Radif, spiritual jazz and the energy of each room.",
    shortBio:
      "Vazesh brings Hamed Sadeghi together with Jeremy Rose and Lloyd Swanton for long-form improvisations shaped by Persian Radif, spiritual jazz, audience and place.",
    achievements: [
      "ARIA-nominated for Best Jazz Album",
      "2021 Art Music Award finalist",
      "Reopened the Sydney Opera House music program with two sold-out shows",
    ],
    websiteUrl: "https://www.hamedsadeghi.com/vazesh",
    source: "website",
    sourceUrl: "https://www.hamedsadeghi.com/vazesh",
    confirmed: false,
  },
  {
    id: "ACT-EMPTY-VOICES",
    name: "Empty Voices",
    shortName: "Empty Voices",
    format: "Large ensemble and orchestral project",
    genres: "Contemporary composition, Persian music, jazz orchestra",
    baseCity: "Sydney, Australia",
    oneLinePitch:
      "A large-ensemble work bringing Persian musical language into dialogue with leading Australian improvisers.",
    shortBio:
      "Empty Voices is Hamed Sadeghi's orchestral project featuring prominent Australian jazz artists and supported in development by Create NSW and the APRA AMCOS Art Music Fund.",
    achievements: [
      "Supported by Create NSW",
      "Supported by the APRA AMCOS Art Music Fund",
    ],
    websiteUrl: "https://www.hamedsadeghi.com/discography/empty-voices",
    source: "website",
    sourceUrl: "https://www.hamedsadeghi.com/about",
    confirmed: false,
  },
  {
    id: "ACT-SCREEN-STAGE",
    name: "Screen and Stage",
    shortName: "Screen & Stage",
    format: "Composer for theatre, film and dance",
    genres: "Original score, theatre, dance, film",
    baseCity: "Sydney, Australia",
    oneLinePitch:
      "Distinctive cross-cultural composition for theatre, film and dance.",
    shortBio:
      "Hamed's composition work includes projects with Belvoir Theatre, Melbourne Theatre Company, Sydney Dance Company and Sydney Film Festival.",
    achievements: [
      "Sydney Theatre Awards nomination for original score",
      "Credits with Belvoir Theatre and Melbourne Theatre Company",
      "Credits with Sydney Dance Company and Sydney Film Festival",
    ],
    websiteUrl: "https://www.hamedsadeghi.com/film/theatre",
    source: "website",
    sourceUrl: "https://www.hamedsadeghi.com/film/theatre",
    confirmed: false,
  },
];

const createdAt = "2026-06-15T00:00:00.000Z";

export const hamedCampaigns: Campaign[] = [
  {
    id: "CAMPAIGN-EISHAN-EU-2026",
    actId: "ACT-EISHAN",
    name: "Eishan Europe Tour 2026",
    type: "Tour",
    status: "Suggested",
    goal: "Build a viable September and October 2026 European route with paid festival and venue dates.",
    startDate: "2026-09-01",
    endDate: "2026-10-31",
    targetRegions: ["Europe", "Germany", "France", "Austria", "Belgium", "Italy", "Portugal", "United Kingdom"],
    minimumFee: "",
    ensembleSize: 4,
    notes:
      "The public website describes this as an upcoming European expansion. Dates remain unconfirmed until Hamed verifies them.",
    source: "website",
    confirmed: false,
    contactIds: [],
    opportunityIds: [],
    tasks: [
      {
        id: "TASK-EU-CONFIRM",
        title: "Confirm tour window, ensemble size and minimum fee",
        status: "To do",
        dueDate: "",
        createdAt,
      },
      {
        id: "TASK-EU-ASSETS",
        title: "Confirm the strongest EPK, live video and technical rider",
        status: "To do",
        dueDate: "",
        createdAt,
      },
    ],
    deals: [],
    expenses: [],
    routeStops: [
      {
        id: "ROUTE-EU-1",
        city: "Europe",
        country: "",
        startDate: "2026-09-01",
        endDate: "2026-09-20",
        status: "Available",
        venue: "",
        notes: "Open routing window",
      },
      {
        id: "ROUTE-EU-2",
        city: "Europe",
        country: "",
        startDate: "2026-09-21",
        endDate: "2026-10-31",
        status: "Available",
        venue: "",
        notes: "Open routing window",
      },
    ],
    requiredAssetKinds: ["EPK", "Music", "Live video", "Biography", "Technical rider"],
    createdAt,
  },
  {
    id: "CAMPAIGN-NORTHERN-RHAPSODY",
    actId: "ACT-EISHAN",
    name: "Northern Rhapsody",
    type: "Release",
    status: "Suggested",
    goal: "Extend the 2025 album story through touring, press and presenter outreach.",
    startDate: "2025-01-01",
    endDate: "2026-12-31",
    targetRegions: ["Australia", "Europe"],
    minimumFee: "",
    ensembleSize: 4,
    notes: "Album and touring details are sourced from the Eishan Ensemble website.",
    source: "website",
    confirmed: false,
    contactIds: [],
    opportunityIds: [],
    tasks: [],
    deals: [],
    expenses: [],
    routeStops: [],
    requiredAssetKinds: ["Music", "Biography", "Press quote", "Live video"],
    createdAt,
  },
  {
    id: "CAMPAIGN-SOLO",
    actId: "ACT-HAMED-SOLO",
    name: "Solo Recital and Festival Bookings",
    type: "Bookings",
    status: "Suggested",
    goal: "Find recital, festival and cultural-programming opportunities for solo tar performance.",
    startDate: "",
    endDate: "",
    targetRegions: ["Australia", "Europe"],
    minimumFee: "",
    ensembleSize: 1,
    notes: "",
    source: "website",
    confirmed: false,
    contactIds: [],
    opportunityIds: [],
    tasks: [],
    deals: [],
    expenses: [],
    routeStops: [],
    requiredAssetKinds: ["Biography", "Music", "Live video", "Technical rider"],
    createdAt,
  },
  {
    id: "CAMPAIGN-VAZESH",
    actId: "ACT-VAZESH",
    name: "Vazesh Festival Bookings",
    type: "Bookings",
    status: "Suggested",
    goal: "Find jazz, improvised-music and adventurous festival bookings for Vazesh.",
    startDate: "",
    endDate: "",
    targetRegions: ["Australia", "Europe"],
    minimumFee: "",
    ensembleSize: 3,
    notes: "",
    source: "website",
    confirmed: false,
    contactIds: [],
    opportunityIds: [],
    tasks: [],
    deals: [],
    expenses: [],
    routeStops: [],
    requiredAssetKinds: ["Biography", "Music", "Live video", "Press quote"],
    createdAt,
  },
  {
    id: "CAMPAIGN-COMMISSIONS",
    actId: "ACT-SCREEN-STAGE",
    name: "Composer Commissions",
    type: "Commissions",
    status: "Suggested",
    goal: "Develop new theatre, film and dance composition commissions.",
    startDate: "",
    endDate: "",
    targetRegions: ["Australia"],
    minimumFee: "",
    ensembleSize: 1,
    notes: "",
    source: "website",
    confirmed: false,
    contactIds: [],
    opportunityIds: [],
    tasks: [],
    deals: [],
    expenses: [],
    routeStops: [],
    requiredAssetKinds: ["Biography", "Music", "Website"],
    createdAt,
  },
  {
    id: "CAMPAIGN-EMPTY-VOICES",
    actId: "ACT-EMPTY-VOICES",
    name: "Empty Voices Presenters and Funding",
    type: "Funding",
    status: "Suggested",
    goal: "Find presenters, co-commissioners and funding routes for the large-ensemble work.",
    startDate: "",
    endDate: "",
    targetRegions: ["Australia"],
    minimumFee: "",
    ensembleSize: 8,
    notes: "Ensemble size is an editable planning assumption.",
    source: "website",
    confirmed: false,
    contactIds: [],
    opportunityIds: [],
    tasks: [],
    deals: [],
    expenses: [],
    routeStops: [],
    requiredAssetKinds: ["Biography", "Music", "EPK", "Technical rider"],
    createdAt,
  },
];

export const hamedAssets: ArtistAsset[] = [
  {
    id: "ASSET-EISHAN-WEBSITE",
    actId: "ACT-EISHAN",
    kind: "Website",
    label: "Eishan Ensemble website",
    value: "https://www.eishanensemble.com",
    source: "website",
    verified: true,
  },
  {
    id: "ASSET-EISHAN-MUSIC",
    actId: "ACT-EISHAN",
    kind: "Music",
    label: "Northern Rhapsody",
    value: "https://bfan.link/northern-rhapsody",
    source: "website",
    verified: true,
  },
  {
    id: "ASSET-HAMED-WEBSITE",
    actId: "ACT-HAMED-SOLO",
    kind: "Website",
    label: "Hamed Sadeghi website",
    value: "https://www.hamedsadeghi.com",
    source: "website",
    verified: true,
  },
  {
    id: "ASSET-EISHAN-QUOTE",
    actId: "ACT-EISHAN",
    kind: "Press quote",
    label: "Sydney Morning Herald",
    value: "One of the best composers in Australia",
    source: "website",
    verified: false,
  },
];

export function actToArtistProfile(
  workspace: ArtistWorkspace,
  act: ActProfile,
  campaign?: Campaign,
  assets: ArtistAsset[] = [],
): ArtistProfile {
  const actAssets = assets.filter((asset) => asset.actId === act.id);
  const findAsset = (kind: ArtistAsset["kind"]) =>
    actAssets.find((asset) => asset.kind === kind)?.value || "";
  return {
    artistName: workspace.ownerName,
    projectName: act.name,
    baseCity: act.baseCity,
    genres: act.genres,
    oneLinePitch: act.oneLinePitch,
    shortBio: act.shortBio,
    currentProject: campaign ? `${campaign.name}: ${campaign.goal}` : "",
    careerGoals: campaign?.goal || "",
    websiteUrl: act.websiteUrl,
    musicUrl: findAsset("Music"),
    liveVideoUrl: findAsset("Live video"),
    pressKitUrl: findAsset("EPK"),
    signatureName: workspace.signatureName,
    defaultFee: campaign?.minimumFee || "",
  };
}
